use crate::engine::DiffReport;

/// Generates a rich GitHub Actions PR Markdown comment from diff reports.
pub fn generate_pr_comment_markdown(reports: &[DiffReport], total_duration_ms: u64) -> String {
    let mut out = String::new();

    let total = reports.len();
    let passed = reports.iter().filter(|r| r.passed()).count();
    let failed = total - passed;

    out.push_str("## 📸 ApiSnap Regression Test Summary\n\n");

    if failed == 0 {
        out.push_str(&format!(
            "> **✅ All {} API endpoints matched their golden snapshots** in `{}ms`.\n\n",
            total, total_duration_ms
        ));
    } else {
        out.push_str(&format!(
            "> **❌ Snapshot Regression Detected**: `{} / {}` endpoints failed contract verification (`{}ms`).\n\n",
            failed, total, total_duration_ms
        ));
    }

    out.push_str("| Status | Endpoint | Expected | Actual | Differences |\n");
    out.push_str("| :---: | :--- | :---: | :---: | :---: |\n");

    for r in reports {
        let status_icon = if r.passed() { "🟢 PASS" } else { "🔴 FAIL" };
        let diff_count = r.differences.len();
        out.push_str(&format!(
            "| {} | `{}` | `{}` | `{}` | `{}` |\n",
            status_icon, r.endpoint_name, r.expected_status, r.actual_status, diff_count
        ));
    }

    // Detailed collapsible diffs for failed endpoints
    for r in reports.iter().filter(|r| !r.passed()) {
        out.push_str(&format!("\n<details>\n<summary><b>🔍 View Diff Details: <code>{}</code></b></summary>\n\n", r.endpoint_name));
        out.push_str("```diff\n");
        for diff in &r.differences {
            match diff {
                crate::engine::DiffKind::Added { json_path, new_value } => {
                    out.push_str(&format!("+ {}: {}\n", json_path, new_value));
                }
                crate::engine::DiffKind::Removed { json_path, old_value } => {
                    out.push_str(&format!("- {}: {}\n", json_path, old_value));
                }
                crate::engine::DiffKind::Modified { json_path, old_value, new_value } => {
                    out.push_str(&format!("~ {}\n- {}\n+ {}\n", json_path, old_value, new_value));
                }
                crate::engine::DiffKind::TypeMismatch { json_path, expected_type, actual_type, .. } => {
                    out.push_str(&format!("! {} (type mismatch: expected {}, got {})\n", json_path, expected_type, actual_type));
                }
                crate::engine::DiffKind::ArrayLengthMismatch { json_path, expected_len, actual_len } => {
                    out.push_str(&format!("~ {} (array length changed: {} -> {})\n", json_path, expected_len, actual_len));
                }
                crate::engine::DiffKind::DepthExceeded { json_path, max_depth } => {
                    out.push_str(&format!("! {} (max depth {} exceeded)\n", json_path, max_depth));
                }
            }
        }
        out.push_str("```\n\n");
        out.push_str("To accept this change, run:\n");
        out.push_str(&format!("```bash\napisnap review --endpoint {}\n```\n", r.endpoint_name));
        out.push_str("</details>\n");
    }

    out.push_str("\n---\n*Generated by [ApiSnap](https://github.com/xylt369/apisnap) • Automated API Contract Regression Guard*\n");
    out
}
